version: "3.1"
services:
  memcached:
    image: memcached:latest
    container_name: project-memcached
    networks:
      - default

  db:
    image: mariadb:latest
    container_name: project-mysql
    working_dir: /application
    volumes:
      - .:/application
      - ./db:/var/lib/mysql # will create /db folder with database datafiles
    environment:
      - MYSQL_ROOT_PASSWORD=project
      - MYSQL_DATABASE=project
      - MYSQL_USER=project
      - MYSQL_PASSWORD=project
    ports:
      - "3306:3306"
    networks:
      - default

  webserver:
    image: nginx:alpine
    container_name: project-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      XDEBUG_SESSION: 1
      VIRTUAL_HOST: "project.localhost" # add this hostname in /etc/hosts to reverse proxy resolve
      VIRTUAL_POST: "8888"
      SELF_SIGNED_HOST: "project.localhost" # https support via self-signed-proxy-companion to nginx
    depends_on:
      - db
    networks:
      - default

  php-fpm:
    build: phpdocker/php-fpm
    container_name: project-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini # php 7.4
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    external:
      name: tsuNet # if 'tsuNet' not exists: $ docker network create tsuNet

